apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-deployer-role
  namespace: app-prod
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-deployer-binding
  namespace: app-prod
subjects:
  - kind: User
    name: prod-deployer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-deployer-role
  apiGroup: rbac.authorization.k8s.io
